// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package session

import (
	"context"
)

const clearRuns = `-- name: ClearRuns :exec
DELETE FROM runs
`

func (q *Queries) ClearRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearRuns)
	return err
}

const clearSessions = `-- name: ClearSessions :exec
DELETE FROM sessions
`

func (q *Queries) ClearSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSessions)
	return err
}

const getSession = `-- name: GetSession :one
SELECT payload FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var payload string
	err := row.Scan(&payload)
	return payload, err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (session_id, seq, owner, payload) VALUES ($1, $2, $3, $4)
`

type InsertRunParams struct {
	SessionID string
	Seq       int64
	Owner     string
	Payload   string
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRun,
		arg.SessionID,
		arg.Seq,
		arg.Owner,
		arg.Payload,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, owner, payload) VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	ID      string
	Owner   string
	Payload string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession, arg.ID, arg.Owner, arg.Payload)
	return err
}

const listRuns = `-- name: ListRuns :many
SELECT session_id, seq, payload FROM runs ORDER BY position
`

type ListRunsRow struct {
	SessionID string
	Seq       int64
	Payload   string
}

func (q *Queries) ListRuns(ctx context.Context) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(&i.SessionID, &i.Seq, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByOwner = `-- name: ListRunsByOwner :many
SELECT session_id, seq, payload FROM runs WHERE owner = $1 ORDER BY position
`

type ListRunsByOwnerRow struct {
	SessionID string
	Seq       int64
	Payload   string
}

func (q *Queries) ListRunsByOwner(ctx context.Context, owner string) ([]ListRunsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsByOwnerRow
	for rows.Next() {
		var i ListRunsByOwnerRow
		if err := rows.Scan(&i.SessionID, &i.Seq, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, payload FROM sessions ORDER BY id
`

type ListSessionsRow struct {
	ID      string
	Payload string
}

func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(&i.ID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByOwner = `-- name: ListSessionsByOwner :many
SELECT id, payload FROM sessions WHERE owner = $1 ORDER BY id
`

type ListSessionsByOwnerRow struct {
	ID      string
	Payload string
}

func (q *Queries) ListSessionsByOwner(ctx context.Context, owner string) ([]ListSessionsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByOwnerRow
	for rows.Next() {
		var i ListSessionsByOwnerRow
		if err := rows.Scan(&i.ID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
