// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package session

import (
	"database/sql"
)

type runRow struct {
	Position  sql.NullInt64
	SessionID string
	Seq       int64
	Owner     string
	Payload   string
}

type sessionRow struct {
	ID      string
	Owner   string
	Payload string
}
