// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package session

type runRow struct {
	SessionID string
	Seq       int64
	Owner     string
	Payload   string
}

type sessionRow struct {
	ID      string
	Owner   string
	Payload string
}
