// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package ssh

import (
	"context"
)

const deleteHost = `-- name: DeleteHost :execrows
DELETE FROM ssh_hosts WHERE principal = ? AND host = ? COLLATE BINARY
`

type DeleteHostParams struct {
	Principal string
	Host      string
}

func (q *Queries) DeleteHost(ctx context.Context, arg DeleteHostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHost, arg.Principal, arg.Host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteKey = `-- name: DeleteKey :execrows
DELETE FROM ssh_keys WHERE principal = ? AND name = ?
`

type DeleteKeyParams struct {
	Principal string
	Name      string
}

func (q *Queries) DeleteKey(ctx context.Context, arg DeleteKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKey, arg.Principal, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getKey = `-- name: GetKey :one
SELECT name, type, fingerprint FROM ssh_keys WHERE principal = ? AND name = ?
`

type GetKeyParams struct {
	Principal string
	Name      string
}

type GetKeyRow struct {
	Name        string
	Type        string
	Fingerprint string
}

func (q *Queries) GetKey(ctx context.Context, arg GetKeyParams) (GetKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getKey, arg.Principal, arg.Name)
	var i GetKeyRow
	err := row.Scan(&i.Name, &i.Type, &i.Fingerprint)
	return i, err
}

const insertHost = `-- name: InsertHost :exec
INSERT INTO ssh_hosts (principal, host, payload) VALUES (?, ?, ?)
`

type InsertHostParams struct {
	Principal string
	Host      string
	Payload   string
}

func (q *Queries) InsertHost(ctx context.Context, arg InsertHostParams) error {
	_, err := q.db.ExecContext(ctx, insertHost, arg.Principal, arg.Host, arg.Payload)
	return err
}

const insertKey = `-- name: InsertKey :exec
INSERT INTO ssh_keys (principal, name, type, fingerprint) VALUES (?, ?, ?, ?)
`

type InsertKeyParams struct {
	Principal   string
	Name        string
	Type        string
	Fingerprint string
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertKey,
		arg.Principal,
		arg.Name,
		arg.Type,
		arg.Fingerprint,
	)
	return err
}

const listHostPrincipals = `-- name: ListHostPrincipals :many
SELECT DISTINCT principal FROM ssh_hosts ORDER BY principal
`

func (q *Queries) ListHostPrincipals(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHostPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var principal string
		if err := rows.Scan(&principal); err != nil {
			return nil, err
		}
		items = append(items, principal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHosts = `-- name: ListHosts :many
SELECT host, payload FROM ssh_hosts WHERE principal = ? ORDER BY host
`

type ListHostsRow struct {
	Host    string
	Payload string
}

func (q *Queries) ListHosts(ctx context.Context, principal string) ([]ListHostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHosts, principal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHostsRow
	for rows.Next() {
		var i ListHostsRow
		if err := rows.Scan(&i.Host, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT name, type, fingerprint FROM ssh_keys WHERE principal = ? ORDER BY name
`

type ListKeysRow struct {
	Name        string
	Type        string
	Fingerprint string
}

func (q *Queries) ListKeys(ctx context.Context, principal string) ([]ListKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeys, principal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKeysRow
	for rows.Next() {
		var i ListKeysRow
		if err := rows.Scan(&i.Name, &i.Type, &i.Fingerprint); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHost = `-- name: UpdateHost :execrows
UPDATE ssh_hosts SET payload = ? WHERE principal = ? AND host = ? COLLATE BINARY
`

type UpdateHostParams struct {
	Payload   string
	Principal string
	Host      string
}

func (q *Queries) UpdateHost(ctx context.Context, arg UpdateHostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHost, arg.Payload, arg.Principal, arg.Host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
