// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ssh

type hostRow struct {
	Principal string
	Host      string
	Payload   string
}

type keyRow struct {
	Principal   string
	Name        string
	Type        string
	Fingerprint string
}
